(function (unit, model) {

	/*
	 * JavaScript code generated by mendixmodelsdk.sdk.extras.JavaScriptSerializer
	 * from unit with id "56a12f07-9b3a-45d6-9b3c-0c8859779561" of type Pages$Page
	 * in working copy "PDFImporter"
	 * on 30-7-2024.
	 */

	var objectType1 = datatypes.ObjectType.create(model);
	objectType1.entity = model.findEntityByQualifiedName("SampleModule.Everything");

	var everything1 = pages.PageParameter.create(model);
	everything1.name = "Everything";
	everything1.parameterType = objectType1;   // Note: for this property a default value is defined.

	var appearance1 = pages.Appearance.create(model);

	var appearance2 = pages.Appearance.create(model);

	var directEntityRef1 = domainmodels.DirectEntityRef.create(model);
	directEntityRef1.entity = model.findEntityByQualifiedName("SampleModule.Everything");

	var pageVariable1 = pages.PageVariable.create(model);

	var dataViewSource1 = pages.DataViewSource.create(model);
	dataViewSource1.entityRef = directEntityRef1;
	dataViewSource1.sourceVariable = pageVariable1;

	var appearance3 = pages.Appearance.create(model);

	var translation1 = texts.Translation.create(model);
	translation1.languageCode = "en_US";
	translation1.text = "Attribute boolean";

	var text1 = texts.Text.create(model);
	text1.translations.push(translation1);

	var text2 = texts.Text.create(model);

	var clientTemplate1 = pages.ClientTemplate.create(model);
	clientTemplate1.template = text1;   // Note: for this property a default value is defined.
	clientTemplate1.fallback = text2;   // Note: for this property a default value is defined.

	var attributeRef1 = domainmodels.AttributeRef.create(model);
	attributeRef1.attribute = model.findAttributeByQualifiedName("SampleModule.Everything.AttributeBoolean");

	var text3 = texts.Text.create(model);

	var widgetValidation1 = pages.WidgetValidation.create(model);
	widgetValidation1.message = text3;   // Note: for this property a default value is defined.

	var noClientAction1 = pages.NoClientAction.create(model);

	var noClientAction2 = pages.NoClientAction.create(model);

	var noClientAction3 = pages.NoClientAction.create(model);

	var radioButtons1_1 = pages.RadioButtonGroup.create(model);
	radioButtons1_1.name = "radioButtons1";
	radioButtons1_1.appearance = appearance3;   // Note: for this property a default value is defined.
	radioButtons1_1.labelTemplate = clientTemplate1;
	radioButtons1_1.attributeRef = attributeRef1;
	radioButtons1_1.validation = widgetValidation1;   // Note: for this property a default value is defined.
	radioButtons1_1.onChangeAction = noClientAction1;   // Note: for this property a default value is defined.
	radioButtons1_1.onEnterAction = noClientAction2;   // Note: for this property a default value is defined.
	radioButtons1_1.onLeaveAction = noClientAction3;   // Note: for this property a default value is defined.

	var appearance4 = pages.Appearance.create(model);

	var translation2 = texts.Translation.create(model);
	translation2.languageCode = "en_US";
	translation2.text = "Attribute date time";

	var text4 = texts.Text.create(model);
	text4.translations.push(translation2);

	var text5 = texts.Text.create(model);

	var clientTemplate2 = pages.ClientTemplate.create(model);
	clientTemplate2.template = text4;   // Note: for this property a default value is defined.
	clientTemplate2.fallback = text5;   // Note: for this property a default value is defined.

	var attributeRef2 = domainmodels.AttributeRef.create(model);
	attributeRef2.attribute = model.findAttributeByQualifiedName("SampleModule.Everything.AttributeDateTime");

	var text6 = texts.Text.create(model);

	var widgetValidation2 = pages.WidgetValidation.create(model);
	widgetValidation2.message = text6;   // Note: for this property a default value is defined.

	var noClientAction4 = pages.NoClientAction.create(model);

	var noClientAction5 = pages.NoClientAction.create(model);

	var noClientAction6 = pages.NoClientAction.create(model);

	var text7 = texts.Text.create(model);

	var text8 = texts.Text.create(model);

	var clientTemplate3 = pages.ClientTemplate.create(model);
	clientTemplate3.template = text7;   // Note: for this property a default value is defined.
	clientTemplate3.fallback = text8;   // Note: for this property a default value is defined.

	var formattingInfo1 = pages.FormattingInfo.create(model);

	var datePicker1_1 = pages.DatePicker.create(model);
	datePicker1_1.name = "datePicker1";
	datePicker1_1.appearance = appearance4;   // Note: for this property a default value is defined.
	datePicker1_1.labelTemplate = clientTemplate2;
	datePicker1_1.attributeRef = attributeRef2;
	datePicker1_1.validation = widgetValidation2;   // Note: for this property a default value is defined.
	datePicker1_1.onChangeAction = noClientAction4;   // Note: for this property a default value is defined.
	datePicker1_1.onEnterAction = noClientAction5;   // Note: for this property a default value is defined.
	datePicker1_1.onLeaveAction = noClientAction6;   // Note: for this property a default value is defined.
	datePicker1_1.placeholderTemplate = clientTemplate3;   // Note: for this property a default value is defined.
	datePicker1_1.formattingInfo = formattingInfo1;   // Note: for this property a default value is defined.

	var appearance5 = pages.Appearance.create(model);

	var translation3 = texts.Translation.create(model);
	translation3.languageCode = "en_US";
	translation3.text = "Attribute decimal";

	var text9 = texts.Text.create(model);
	text9.translations.push(translation3);

	var text10 = texts.Text.create(model);

	var clientTemplate4 = pages.ClientTemplate.create(model);
	clientTemplate4.template = text9;   // Note: for this property a default value is defined.
	clientTemplate4.fallback = text10;   // Note: for this property a default value is defined.

	var attributeRef3 = domainmodels.AttributeRef.create(model);
	attributeRef3.attribute = model.findAttributeByQualifiedName("SampleModule.Everything.AttributeDecimal");

	var text11 = texts.Text.create(model);

	var widgetValidation3 = pages.WidgetValidation.create(model);
	widgetValidation3.message = text11;   // Note: for this property a default value is defined.

	var noClientAction7 = pages.NoClientAction.create(model);

	var noClientAction8 = pages.NoClientAction.create(model);

	var noClientAction9 = pages.NoClientAction.create(model);

	var text12 = texts.Text.create(model);

	var text13 = texts.Text.create(model);

	var clientTemplate5 = pages.ClientTemplate.create(model);
	clientTemplate5.template = text12;   // Note: for this property a default value is defined.
	clientTemplate5.fallback = text13;   // Note: for this property a default value is defined.

	var formattingInfo2 = pages.FormattingInfo.create(model);

	var noClientAction10 = pages.NoClientAction.create(model);

	var textBox1_1 = pages.TextBox.create(model);
	textBox1_1.name = "textBox1";
	textBox1_1.appearance = appearance5;   // Note: for this property a default value is defined.
	textBox1_1.labelTemplate = clientTemplate4;
	textBox1_1.attributeRef = attributeRef3;
	textBox1_1.validation = widgetValidation3;   // Note: for this property a default value is defined.
	textBox1_1.onChangeAction = noClientAction7;   // Note: for this property a default value is defined.
	textBox1_1.onEnterAction = noClientAction8;   // Note: for this property a default value is defined.
	textBox1_1.onLeaveAction = noClientAction9;   // Note: for this property a default value is defined.
	textBox1_1.placeholderTemplate = clientTemplate5;   // Note: for this property a default value is defined.
	textBox1_1.formattingInfo = formattingInfo2;   // Note: for this property a default value is defined.
	textBox1_1.onEnterKeyPressAction = noClientAction10;   // Note: for this property a default value is defined.

	var appearance6 = pages.Appearance.create(model);

	var translation4 = texts.Translation.create(model);
	translation4.languageCode = "en_US";
	translation4.text = "Attribute enum";

	var text14 = texts.Text.create(model);
	text14.translations.push(translation4);

	var text15 = texts.Text.create(model);

	var clientTemplate6 = pages.ClientTemplate.create(model);
	clientTemplate6.template = text14;   // Note: for this property a default value is defined.
	clientTemplate6.fallback = text15;   // Note: for this property a default value is defined.

	var attributeRef4 = domainmodels.AttributeRef.create(model);
	attributeRef4.attribute = model.findAttributeByQualifiedName("SampleModule.Everything.AttributeEnum");

	var text16 = texts.Text.create(model);

	var widgetValidation4 = pages.WidgetValidation.create(model);
	widgetValidation4.message = text16;   // Note: for this property a default value is defined.

	var noClientAction11 = pages.NoClientAction.create(model);

	var noClientAction12 = pages.NoClientAction.create(model);

	var noClientAction13 = pages.NoClientAction.create(model);

	var radioButtons2_1 = pages.RadioButtonGroup.create(model);
	radioButtons2_1.name = "radioButtons2";
	radioButtons2_1.appearance = appearance6;   // Note: for this property a default value is defined.
	radioButtons2_1.labelTemplate = clientTemplate6;
	radioButtons2_1.attributeRef = attributeRef4;
	radioButtons2_1.validation = widgetValidation4;   // Note: for this property a default value is defined.
	radioButtons2_1.onChangeAction = noClientAction11;   // Note: for this property a default value is defined.
	radioButtons2_1.onEnterAction = noClientAction12;   // Note: for this property a default value is defined.
	radioButtons2_1.onLeaveAction = noClientAction13;   // Note: for this property a default value is defined.

	var appearance7 = pages.Appearance.create(model);

	var translation5 = texts.Translation.create(model);
	translation5.languageCode = "en_US";
	translation5.text = "Attribute integer";

	var text17 = texts.Text.create(model);
	text17.translations.push(translation5);

	var text18 = texts.Text.create(model);

	var clientTemplate7 = pages.ClientTemplate.create(model);
	clientTemplate7.template = text17;   // Note: for this property a default value is defined.
	clientTemplate7.fallback = text18;   // Note: for this property a default value is defined.

	var attributeRef5 = domainmodels.AttributeRef.create(model);
	attributeRef5.attribute = model.findAttributeByQualifiedName("SampleModule.Everything.AttributeInteger");

	var text19 = texts.Text.create(model);

	var widgetValidation5 = pages.WidgetValidation.create(model);
	widgetValidation5.message = text19;   // Note: for this property a default value is defined.

	var noClientAction14 = pages.NoClientAction.create(model);

	var noClientAction15 = pages.NoClientAction.create(model);

	var noClientAction16 = pages.NoClientAction.create(model);

	var text20 = texts.Text.create(model);

	var text21 = texts.Text.create(model);

	var clientTemplate8 = pages.ClientTemplate.create(model);
	clientTemplate8.template = text20;   // Note: for this property a default value is defined.
	clientTemplate8.fallback = text21;   // Note: for this property a default value is defined.

	var formattingInfo3 = pages.FormattingInfo.create(model);

	var noClientAction17 = pages.NoClientAction.create(model);

	var textBox2_1 = pages.TextBox.create(model);
	textBox2_1.name = "textBox2";
	textBox2_1.appearance = appearance7;   // Note: for this property a default value is defined.
	textBox2_1.labelTemplate = clientTemplate7;
	textBox2_1.attributeRef = attributeRef5;
	textBox2_1.validation = widgetValidation5;   // Note: for this property a default value is defined.
	textBox2_1.onChangeAction = noClientAction14;   // Note: for this property a default value is defined.
	textBox2_1.onEnterAction = noClientAction15;   // Note: for this property a default value is defined.
	textBox2_1.onLeaveAction = noClientAction16;   // Note: for this property a default value is defined.
	textBox2_1.placeholderTemplate = clientTemplate8;   // Note: for this property a default value is defined.
	textBox2_1.formattingInfo = formattingInfo3;   // Note: for this property a default value is defined.
	textBox2_1.onEnterKeyPressAction = noClientAction17;   // Note: for this property a default value is defined.

	var appearance8 = pages.Appearance.create(model);

	var translation6 = texts.Translation.create(model);
	translation6.languageCode = "en_US";
	translation6.text = "Attribute long";

	var text22 = texts.Text.create(model);
	text22.translations.push(translation6);

	var text23 = texts.Text.create(model);

	var clientTemplate9 = pages.ClientTemplate.create(model);
	clientTemplate9.template = text22;   // Note: for this property a default value is defined.
	clientTemplate9.fallback = text23;   // Note: for this property a default value is defined.

	var attributeRef6 = domainmodels.AttributeRef.create(model);
	attributeRef6.attribute = model.findAttributeByQualifiedName("SampleModule.Everything.AttributeLong");

	var text24 = texts.Text.create(model);

	var widgetValidation6 = pages.WidgetValidation.create(model);
	widgetValidation6.message = text24;   // Note: for this property a default value is defined.

	var noClientAction18 = pages.NoClientAction.create(model);

	var noClientAction19 = pages.NoClientAction.create(model);

	var noClientAction20 = pages.NoClientAction.create(model);

	var text25 = texts.Text.create(model);

	var text26 = texts.Text.create(model);

	var clientTemplate10 = pages.ClientTemplate.create(model);
	clientTemplate10.template = text25;   // Note: for this property a default value is defined.
	clientTemplate10.fallback = text26;   // Note: for this property a default value is defined.

	var formattingInfo4 = pages.FormattingInfo.create(model);

	var noClientAction21 = pages.NoClientAction.create(model);

	var textBox3_1 = pages.TextBox.create(model);
	textBox3_1.name = "textBox3";
	textBox3_1.appearance = appearance8;   // Note: for this property a default value is defined.
	textBox3_1.labelTemplate = clientTemplate9;
	textBox3_1.attributeRef = attributeRef6;
	textBox3_1.validation = widgetValidation6;   // Note: for this property a default value is defined.
	textBox3_1.onChangeAction = noClientAction18;   // Note: for this property a default value is defined.
	textBox3_1.onEnterAction = noClientAction19;   // Note: for this property a default value is defined.
	textBox3_1.onLeaveAction = noClientAction20;   // Note: for this property a default value is defined.
	textBox3_1.placeholderTemplate = clientTemplate10;   // Note: for this property a default value is defined.
	textBox3_1.formattingInfo = formattingInfo4;   // Note: for this property a default value is defined.
	textBox3_1.onEnterKeyPressAction = noClientAction21;   // Note: for this property a default value is defined.

	var appearance9 = pages.Appearance.create(model);

	var translation7 = texts.Translation.create(model);
	translation7.languageCode = "en_US";
	translation7.text = "Attribute string";

	var text27 = texts.Text.create(model);
	text27.translations.push(translation7);

	var text28 = texts.Text.create(model);

	var clientTemplate11 = pages.ClientTemplate.create(model);
	clientTemplate11.template = text27;   // Note: for this property a default value is defined.
	clientTemplate11.fallback = text28;   // Note: for this property a default value is defined.

	var attributeRef7 = domainmodels.AttributeRef.create(model);
	attributeRef7.attribute = model.findAttributeByQualifiedName("SampleModule.Everything.AttributeString");

	var text29 = texts.Text.create(model);

	var widgetValidation7 = pages.WidgetValidation.create(model);
	widgetValidation7.message = text29;   // Note: for this property a default value is defined.

	var noClientAction22 = pages.NoClientAction.create(model);

	var noClientAction23 = pages.NoClientAction.create(model);

	var noClientAction24 = pages.NoClientAction.create(model);

	var text30 = texts.Text.create(model);

	var text31 = texts.Text.create(model);

	var clientTemplate12 = pages.ClientTemplate.create(model);
	clientTemplate12.template = text30;   // Note: for this property a default value is defined.
	clientTemplate12.fallback = text31;   // Note: for this property a default value is defined.

	var formattingInfo5 = pages.FormattingInfo.create(model);

	var noClientAction25 = pages.NoClientAction.create(model);

	var textBox4_1 = pages.TextBox.create(model);
	textBox4_1.name = "textBox4";
	textBox4_1.appearance = appearance9;   // Note: for this property a default value is defined.
	textBox4_1.labelTemplate = clientTemplate11;
	textBox4_1.attributeRef = attributeRef7;
	textBox4_1.validation = widgetValidation7;   // Note: for this property a default value is defined.
	textBox4_1.onChangeAction = noClientAction22;   // Note: for this property a default value is defined.
	textBox4_1.onEnterAction = noClientAction23;   // Note: for this property a default value is defined.
	textBox4_1.onLeaveAction = noClientAction24;   // Note: for this property a default value is defined.
	textBox4_1.placeholderTemplate = clientTemplate12;   // Note: for this property a default value is defined.
	textBox4_1.formattingInfo = formattingInfo5;   // Note: for this property a default value is defined.
	textBox4_1.onEnterKeyPressAction = noClientAction25;   // Note: for this property a default value is defined.

	var appearance10 = pages.Appearance.create(model);

	var translation8 = texts.Translation.create(model);
	translation8.languageCode = "en_US";
	translation8.text = "Save";

	var text32 = texts.Text.create(model);
	text32.translations.push(translation8);

	var text33 = texts.Text.create(model);

	var clientTemplate13 = pages.ClientTemplate.create(model);
	clientTemplate13.template = text32;   // Note: for this property a default value is defined.
	clientTemplate13.fallback = text33;   // Note: for this property a default value is defined.

	var text34 = texts.Text.create(model);

	var saveChangesClientAction1 = pages.SaveChangesClientAction.create(model);

	var actionButton1_1 = pages.ActionButton.create(model);
	actionButton1_1.name = "actionButton1";
	actionButton1_1.appearance = appearance10;   // Note: for this property a default value is defined.
	actionButton1_1.caption = clientTemplate13;   // Note: for this property a default value is defined.
	actionButton1_1.tooltip = text34;   // Note: for this property a default value is defined.
	actionButton1_1.buttonStyle = pages.ButtonStyle.Success;
	actionButton1_1.action = saveChangesClientAction1;   // Note: for this property a default value is defined.

	var appearance11 = pages.Appearance.create(model);

	var translation9 = texts.Translation.create(model);
	translation9.languageCode = "en_US";
	translation9.text = "Cancel";

	var text35 = texts.Text.create(model);
	text35.translations.push(translation9);

	var text36 = texts.Text.create(model);

	var clientTemplate14 = pages.ClientTemplate.create(model);
	clientTemplate14.template = text35;   // Note: for this property a default value is defined.
	clientTemplate14.fallback = text36;   // Note: for this property a default value is defined.

	var text37 = texts.Text.create(model);

	var cancelChangesClientAction1 = pages.CancelChangesClientAction.create(model);

	var actionButton2_1 = pages.ActionButton.create(model);
	actionButton2_1.name = "actionButton2";
	actionButton2_1.appearance = appearance11;   // Note: for this property a default value is defined.
	actionButton2_1.caption = clientTemplate14;   // Note: for this property a default value is defined.
	actionButton2_1.tooltip = text37;   // Note: for this property a default value is defined.
	actionButton2_1.action = cancelChangesClientAction1;   // Note: for this property a default value is defined.

	var text38 = texts.Text.create(model);

	var dataView1_1 = pages.DataView.create(model);
	dataView1_1.name = "dataView1";
	dataView1_1.appearance = appearance2;   // Note: for this property a default value is defined.
	dataView1_1.dataSource = dataViewSource1;
	dataView1_1.widgets.push(radioButtons1_1);
	dataView1_1.widgets.push(datePicker1_1);
	dataView1_1.widgets.push(textBox1_1);
	dataView1_1.widgets.push(radioButtons2_1);
	dataView1_1.widgets.push(textBox2_1);
	dataView1_1.widgets.push(textBox3_1);
	dataView1_1.widgets.push(textBox4_1);
	dataView1_1.footerWidgets.push(actionButton1_1);
	dataView1_1.footerWidgets.push(actionButton2_1);
	dataView1_1.noEntityMessage = text38;   // Note: for this property a default value is defined.

	var appearance12 = pages.Appearance.create(model);

	var layoutGridColumn1 = pages.LayoutGridColumn.create(model);
	layoutGridColumn1.weight = -1;
	layoutGridColumn1.widgets.push(dataView1_1);
	layoutGridColumn1.appearance = appearance12;   // Note: for this property a default value is defined.

	var appearance13 = pages.Appearance.create(model);

	var layoutGridRow1 = pages.LayoutGridRow.create(model);
	layoutGridRow1.columns.push(layoutGridColumn1);
	layoutGridRow1.appearance = appearance13;   // Note: for this property a default value is defined.

	var layoutGrid1_1 = pages.LayoutGrid.create(model);
	layoutGrid1_1.name = "layoutGrid1";
	layoutGrid1_1.appearance = appearance1;   // Note: for this property a default value is defined.
	layoutGrid1_1.rows.push(layoutGridRow1);

	var layoutCallArgument1 = pages.LayoutCallArgument.create(model);
	// Note: this is an unsupported internal property of the Model SDK which is subject to change.
	layoutCallArgument1.__parameter.updateWithRawValue("Atlas_Core.PopupLayout.Main");
	layoutCallArgument1.widgets.push(layoutGrid1_1);

	var layoutCall1 = pages.LayoutCall.create(model);
	layoutCall1.layout = model.findLayoutByQualifiedName("Atlas_Core.PopupLayout");
	layoutCall1.arguments.push(layoutCallArgument1);

	var translation10 = texts.Translation.create(model);
	translation10.languageCode = "en_US";
	translation10.text = "Edit Everything";

	var text39 = texts.Text.create(model);
	text39.translations.push(translation10);

	var appearance14 = pages.Appearance.create(model);

	var everything_NewEdit1 = pages.Page.createIn(unit);
	everything_NewEdit1.name = "Everything_NewEdit";
	everything_NewEdit1.parameters.push(everything1);
	everything_NewEdit1.layoutCall = layoutCall1;   // Note: for this property a default value is defined.
	everything_NewEdit1.title = text39;   // Note: for this property a default value is defined.
	everything_NewEdit1.appearance = appearance14;   // Note: for this property a default value is defined.

	pageVariable1.pageParameter = everything1;

})