(function (unit, model) {

	/*
	 * JavaScript code generated by mendixmodelsdk.sdk.extras.JavaScriptSerializer
	 * from unit with id "f538465e-8344-46d2-bbc4-2716332714bd" of type Pages$Page
	 * in working copy "PDFImporter"
	 * on 30-7-2024.
	 */

	var objectType1 = datatypes.ObjectType.create(model);
	objectType1.entity = model.findEntityByQualifiedName("SampleModule.Sample");

	var sample1 = pages.PageParameter.create(model);
	sample1.name = "Sample";
	sample1.parameterType = objectType1;   // Note: for this property a default value is defined.

	var appearance1 = pages.Appearance.create(model);

	var appearance2 = pages.Appearance.create(model);

	var directEntityRef1 = domainmodels.DirectEntityRef.create(model);
	directEntityRef1.entity = model.findEntityByQualifiedName("SampleModule.Sample");

	var pageVariable1 = pages.PageVariable.create(model);

	var dataViewSource1 = pages.DataViewSource.create(model);
	dataViewSource1.entityRef = directEntityRef1;
	dataViewSource1.sourceVariable = pageVariable1;

	var appearance3 = pages.Appearance.create(model);

	var translation1 = texts.Translation.create(model);
	translation1.languageCode = "en_US";
	translation1.text = "Name";

	var text1 = texts.Text.create(model);
	text1.translations.push(translation1);

	var text2 = texts.Text.create(model);

	var clientTemplate1 = pages.ClientTemplate.create(model);
	clientTemplate1.template = text1;   // Note: for this property a default value is defined.
	clientTemplate1.fallback = text2;   // Note: for this property a default value is defined.

	var attributeRef1 = domainmodels.AttributeRef.create(model);
	attributeRef1.attribute = model.findAttributeByQualifiedName("SampleModule.Sample.Name");

	var text3 = texts.Text.create(model);

	var widgetValidation1 = pages.WidgetValidation.create(model);
	widgetValidation1.message = text3;   // Note: for this property a default value is defined.

	var noClientAction1 = pages.NoClientAction.create(model);

	var noClientAction2 = pages.NoClientAction.create(model);

	var noClientAction3 = pages.NoClientAction.create(model);

	var text4 = texts.Text.create(model);

	var text5 = texts.Text.create(model);

	var clientTemplate2 = pages.ClientTemplate.create(model);
	clientTemplate2.template = text4;   // Note: for this property a default value is defined.
	clientTemplate2.fallback = text5;   // Note: for this property a default value is defined.

	var formattingInfo1 = pages.FormattingInfo.create(model);

	var noClientAction4 = pages.NoClientAction.create(model);

	var textBox1_1 = pages.TextBox.create(model);
	textBox1_1.name = "textBox1";
	textBox1_1.appearance = appearance3;   // Note: for this property a default value is defined.
	textBox1_1.labelTemplate = clientTemplate1;
	textBox1_1.attributeRef = attributeRef1;
	textBox1_1.validation = widgetValidation1;   // Note: for this property a default value is defined.
	textBox1_1.onChangeAction = noClientAction1;   // Note: for this property a default value is defined.
	textBox1_1.onEnterAction = noClientAction2;   // Note: for this property a default value is defined.
	textBox1_1.onLeaveAction = noClientAction3;   // Note: for this property a default value is defined.
	textBox1_1.placeholderTemplate = clientTemplate2;   // Note: for this property a default value is defined.
	textBox1_1.formattingInfo = formattingInfo1;   // Note: for this property a default value is defined.
	textBox1_1.onEnterKeyPressAction = noClientAction4;   // Note: for this property a default value is defined.

	var appearance4 = pages.Appearance.create(model);

	var translation2 = texts.Translation.create(model);
	translation2.languageCode = "en_US";
	translation2.text = "Number";

	var text6 = texts.Text.create(model);
	text6.translations.push(translation2);

	var text7 = texts.Text.create(model);

	var clientTemplate3 = pages.ClientTemplate.create(model);
	clientTemplate3.template = text6;   // Note: for this property a default value is defined.
	clientTemplate3.fallback = text7;   // Note: for this property a default value is defined.

	var attributeRef2 = domainmodels.AttributeRef.create(model);
	attributeRef2.attribute = model.findAttributeByQualifiedName("SampleModule.Sample.Number");

	var text8 = texts.Text.create(model);

	var widgetValidation2 = pages.WidgetValidation.create(model);
	widgetValidation2.message = text8;   // Note: for this property a default value is defined.

	var noClientAction5 = pages.NoClientAction.create(model);

	var noClientAction6 = pages.NoClientAction.create(model);

	var noClientAction7 = pages.NoClientAction.create(model);

	var text9 = texts.Text.create(model);

	var text10 = texts.Text.create(model);

	var clientTemplate4 = pages.ClientTemplate.create(model);
	clientTemplate4.template = text9;   // Note: for this property a default value is defined.
	clientTemplate4.fallback = text10;   // Note: for this property a default value is defined.

	var formattingInfo2 = pages.FormattingInfo.create(model);

	var noClientAction8 = pages.NoClientAction.create(model);

	var textBox2_1 = pages.TextBox.create(model);
	textBox2_1.name = "textBox2";
	textBox2_1.appearance = appearance4;   // Note: for this property a default value is defined.
	textBox2_1.labelTemplate = clientTemplate3;
	textBox2_1.attributeRef = attributeRef2;
	textBox2_1.validation = widgetValidation2;   // Note: for this property a default value is defined.
	textBox2_1.onChangeAction = noClientAction5;   // Note: for this property a default value is defined.
	textBox2_1.onEnterAction = noClientAction6;   // Note: for this property a default value is defined.
	textBox2_1.onLeaveAction = noClientAction7;   // Note: for this property a default value is defined.
	textBox2_1.placeholderTemplate = clientTemplate4;   // Note: for this property a default value is defined.
	textBox2_1.formattingInfo = formattingInfo2;   // Note: for this property a default value is defined.
	textBox2_1.onEnterKeyPressAction = noClientAction8;   // Note: for this property a default value is defined.

	var appearance5 = pages.Appearance.create(model);

	var translation3 = texts.Translation.create(model);
	translation3.languageCode = "en_US";
	translation3.text = "Save";

	var text11 = texts.Text.create(model);
	text11.translations.push(translation3);

	var text12 = texts.Text.create(model);

	var clientTemplate5 = pages.ClientTemplate.create(model);
	clientTemplate5.template = text11;   // Note: for this property a default value is defined.
	clientTemplate5.fallback = text12;   // Note: for this property a default value is defined.

	var text13 = texts.Text.create(model);

	var saveChangesClientAction1 = pages.SaveChangesClientAction.create(model);

	var actionButton1_1 = pages.ActionButton.create(model);
	actionButton1_1.name = "actionButton1";
	actionButton1_1.appearance = appearance5;   // Note: for this property a default value is defined.
	actionButton1_1.caption = clientTemplate5;   // Note: for this property a default value is defined.
	actionButton1_1.tooltip = text13;   // Note: for this property a default value is defined.
	actionButton1_1.buttonStyle = pages.ButtonStyle.Success;
	actionButton1_1.action = saveChangesClientAction1;   // Note: for this property a default value is defined.

	var appearance6 = pages.Appearance.create(model);

	var translation4 = texts.Translation.create(model);
	translation4.languageCode = "en_US";
	translation4.text = "Cancel";

	var text14 = texts.Text.create(model);
	text14.translations.push(translation4);

	var text15 = texts.Text.create(model);

	var clientTemplate6 = pages.ClientTemplate.create(model);
	clientTemplate6.template = text14;   // Note: for this property a default value is defined.
	clientTemplate6.fallback = text15;   // Note: for this property a default value is defined.

	var text16 = texts.Text.create(model);

	var cancelChangesClientAction1 = pages.CancelChangesClientAction.create(model);

	var actionButton2_1 = pages.ActionButton.create(model);
	actionButton2_1.name = "actionButton2";
	actionButton2_1.appearance = appearance6;   // Note: for this property a default value is defined.
	actionButton2_1.caption = clientTemplate6;   // Note: for this property a default value is defined.
	actionButton2_1.tooltip = text16;   // Note: for this property a default value is defined.
	actionButton2_1.action = cancelChangesClientAction1;   // Note: for this property a default value is defined.

	var text17 = texts.Text.create(model);

	var dataView6_1 = pages.DataView.create(model);
	dataView6_1.name = "dataView6";
	dataView6_1.appearance = appearance2;   // Note: for this property a default value is defined.
	dataView6_1.dataSource = dataViewSource1;
	dataView6_1.widgets.push(textBox1_1);
	dataView6_1.widgets.push(textBox2_1);
	dataView6_1.footerWidgets.push(actionButton1_1);
	dataView6_1.footerWidgets.push(actionButton2_1);
	dataView6_1.noEntityMessage = text17;   // Note: for this property a default value is defined.
	dataView6_1.labelWidth = 0;

	var appearance7 = pages.Appearance.create(model);

	var layoutGridColumn1 = pages.LayoutGridColumn.create(model);
	layoutGridColumn1.weight = -1;
	layoutGridColumn1.widgets.push(dataView6_1);
	layoutGridColumn1.appearance = appearance7;   // Note: for this property a default value is defined.

	var appearance8 = pages.Appearance.create(model);

	var layoutGridRow1 = pages.LayoutGridRow.create(model);
	layoutGridRow1.columns.push(layoutGridColumn1);
	layoutGridRow1.appearance = appearance8;   // Note: for this property a default value is defined.

	var layoutGrid1_1 = pages.LayoutGrid.create(model);
	layoutGrid1_1.name = "layoutGrid1";
	layoutGrid1_1.appearance = appearance1;   // Note: for this property a default value is defined.
	layoutGrid1_1.rows.push(layoutGridRow1);

	var layoutCallArgument1 = pages.LayoutCallArgument.create(model);
	// Note: this is an unsupported internal property of the Model SDK which is subject to change.
	layoutCallArgument1.__parameter.updateWithRawValue("Atlas_Core.Atlas_Default.Main");
	layoutCallArgument1.widgets.push(layoutGrid1_1);

	var layoutCall1 = pages.LayoutCall.create(model);
	layoutCall1.layout = model.findLayoutByQualifiedName("Atlas_Core.Atlas_Default");
	layoutCall1.arguments.push(layoutCallArgument1);

	var translation5 = texts.Translation.create(model);
	translation5.languageCode = "en_US";
	translation5.text = "Page";

	var text18 = texts.Text.create(model);
	text18.translations.push(translation5);

	var appearance9 = pages.Appearance.create(model);

	var targetPage1 = pages.Page.createIn(unit);
	targetPage1.name = "TargetPage";
	targetPage1.canvasWidth = 1198;
	targetPage1.parameters.push(sample1);
	targetPage1.layoutCall = layoutCall1;   // Note: for this property a default value is defined.
	targetPage1.title = text18;   // Note: for this property a default value is defined.
	targetPage1.appearance = appearance9;   // Note: for this property a default value is defined.

	pageVariable1.pageParameter = sample1;

})